# -*- coding: utf-8 -*-
"""population_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PE5BllgWjL0-Sj0gPOGv630GFvpemAYJ

# **World Population Data Visualization**

## SkillCraft Technology-Data Science Internship

## Task 01

This project visualizes population data obtained from the World Bank.
A bar chart is used to compare the populations of the top 10 most populous countries.

### Dataset

World Bank - Population, total (SP.POP.TOTL)

### Tools Used

- Python
- Pandas
- Matplotlib
- Google Colab
"""

import requests
import pandas as pd
import matplotlib.pyplot as plt

url = "https://api.worldbank.org/v2/country/all/indicator/SP.POP.TOTL?format=json&per_page=20000"

response = requests.get(url)
json_data = response.json()

records = json_data[1]

df = pd.DataFrame(records)

df.head()

df.info()

df.shape

df["country_name"] = df["country"].apply(
    lambda x: x["value"] if isinstance(x, dict) else x
)

df[["country_name", "countryiso3code", "date", "value"]].head()

df["date"] = pd.to_numeric(df["date"], errors="coerce")

df = df.dropna(subset=["value"])

latest_year = int(df["date"].max())

print("Latest available year:", latest_year)

countries_url = "https://api.worldbank.org/v2/country?format=json&per_page=400"

countries_response = requests.get(countries_url)
countries_data = countries_response.json()[1]

countries_data[:2]

country_codes = [
    c["id"]
    for c in countries_data
    if c["region"]["value"] != "Aggregates"
]

print("Number of actual countries:", len(country_codes))

latest_data = df[df["date"] == latest_year].copy()

print("Rows in latest year:", len(latest_data))

latest_data = latest_data[
    latest_data["countryiso3code"].isin(country_codes)
].copy()

print("Actual countries in latest year:", len(latest_data))

top10 = latest_data.sort_values(
    by="value",
    ascending=False
).head(10)

top10[[
    "country_name",
    "countryiso3code",
    "date",
    "value"
]]

top10["population_millions"] = (
    top10["value"] / 1_000_000
)

top10[[
    "country_name",
    "population_millions"
]]

plt.figure(figsize=(12, 6))

bars = plt.bar(
    top10["country_name"],
    top10["population_millions"]
)

plt.title(
    f"Top 10 Most Populous Countries ({latest_year})",
    fontsize=16
)

plt.xlabel("Country", fontsize=12)
plt.ylabel("Population (Millions)", fontsize=12)

plt.xticks(rotation=45)

# Add population values above each bar
for bar in bars:
    height = bar.get_height()

    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height,
        f"{height:.1f}",
        ha="center",
        va="bottom"
    )

plt.tight_layout()

plt.show()

"""## Observations

1. India has the highest population among the top 10 countries, with approximately 1,463.9 million people.

2. China has the second-highest population, with approximately 1,406.6 million people.

3. There is a significant difference between the populations of India and China and those of the remaining countries.

4. The United States ranks third with approximately 341.8 million people.

5. Indonesia, Pakistan, Nigeria, and Brazil have populations between approximately 200 and 300 million.

6. Bangladesh, the Russian Federation, and Ethiopia have populations below 200 million among the selected top 10 countries.

7. The bar chart clearly shows the large variation in population size among the world's most populous countries.

8. The visualization makes it easier to compare population sizes across countries.

## Conclusion

The visualization shows that population is highly concentrated among a few countries, particularly India and China. A bar chart provides an effective way to compare population sizes and identify differences between countries.
"""